all: 
	pdflatex -synctex=1 -halt-on-error -file-line-error -interaction=nonstopmode "test".tex 
	#biber --output_directory output thesis 
	#pdflatex -synctex=1 -interaction=nonstopmode "test".tex
	open test.pdf
